Repository bratislava/mestskakniznica.sk, pull requests merged in 2023-01, with the labels that each got.

#84 Locality details
  next/components/Molecules/LocalityDetails/LocalityDetails.tsx
  next/components/Molecules/LocalityDetails/LocalityDetailsContactUs.tsx
  next/components/Molecules/LocalityDetails/LocalityDetailsServices.tsx
  next/components/Molecules/LocalityDetails/LocalityDetailsWhere.tsx
  next/components/Molecules/Sections.tsx
Labels: needs review :pray:

#83 Dates
  next/.eslintrc.js
  next/components/AppLayout/Navigation/SubnavigationColumn.tsx
  next/components/Atoms/AnimateHeight.tsx
  next/components/Atoms/DateCardDispaly.tsx
  next/components/Atoms/EventDetailsDateBox.tsx
  next/components/Atoms/EventDetailsRow.tsx
  next/components/HomePage/Promos/PromoEventCard.tsx
  next/components/Molecules/EventDetails.tsx
  next/components/Molecules/EventFilters.tsx
  next/components/Molecules/EventListingCard.tsx
  next/components/Molecules/ListingCard.tsx
  next/components/Molecules/LocalityDetails/LocalityDetails.tsx
  next/components/Molecules/Sections.tsx
  next/components/forms/CityLibraryRegistrationForm/index.tsx
  next/components/forms/EventReservationForm/index.tsx
  next/components/forms/ExcursionReservationForm/index.tsx
  next/components/forms/MusicalInstrumentReservationForm/index.tsx
  next/components/forms/ReaderReservationForm/index.tsx
  next/components/forms/SpaceReservationForm/index.tsx
  next/components/forms/TabletReservationForm/index.tsx
  next/components/forms/TheaterTechReservationForm/index.tsx
  next/components/forms/VenueRentalForm/index.tsx
  next/components/pages/BasicDocumentPage.tsx
  next/components/pages/DocumentsPage.tsx
  next/components/pages/blogPostPage.tsx
  next/components/pages/blogPostsPage.tsx
  next/components/pages/eventsListingPage.tsx
  next/components/pages/newsListingPage.tsx
  next/components/styleguide/Stack.tsx
  next/components/ui/ArticleCard/ArticleCard.tsx
  next/components/ui/RowFile/RowFile.tsx
  next/modules/common/FormatDate.tsx
  next/modules/common/FormatEventDateRange.tsx
  next/modules/common/MDatePicker/MDatePicker.css
  next/modules/common/MDatePicker/MDatePicker.tsx
  next/modules/common/MI18nProvider.tsx
  next/package.json
  next/pages/_app.tsx
  next/pages/basic-document/[slug].tsx
  next/styles/index.css
  next/utils/consts.ts
  next/utils/form-constants.ts
  next/utils/local-date.tsx
  next/utils/utils.ts
  next/yarn.lock
Labels: fix & ship :ship:

#81 Styleguide + Accordion
  next/assets/images/business.svg
  next/assets/images/section.svg
  next/components/Atoms/CityLibraryMarkdown.tsx
  next/components/HomePage/SectionFaq.tsx
  next/components/Molecules/LocalityDetails/LocalityDetails.tsx
  next/components/Molecules/Sections.tsx
  next/components/styleguide/Stack.tsx
  next/components/styleguide/StyleguideAccordion.tsx
  next/components/ui/Accordion/Accordion.tsx
  next/components/ui/Faq/Faq.tsx
  next/components/ui/Footer/Footer.tsx
  next/components/ui/SubListing/SubListing.tsx
  next/components/ui/index.ts
  next/modules/common/Accordion.tsx
  next/pages/styleguide.tsx
  next/tailwind.config.js
Labels: fix & ship :ship:

#88 Prettier reformat
  next/components/AppLayout/Navigation/Subnavigation.tsx
  next/components/AppLayout/SkipToContentButton.tsx
  next/components/Atoms/TagToggle.tsx
  next/components/HomePage/SectionLibraryNews.tsx
  next/components/Molecules/Breadcrumbs.tsx
  next/components/Molecules/CookieConsent.tsx
  next/components/forms/AskLibraryForm.tsx/index.tsx
  next/components/forms/BookNotInLibraryForm/index.tsx
  next/components/forms/GiftCardReservationForm/index.tsx
  next/components/forms/ServiceReservationForm/index.tsx
  next/components/pages/ErrorPage.tsx
  next/components/ui/BookNewsDetail/BookNewsDetail.tsx
  next/components/ui/Breadcrumbs/Breadcrumbs.tsx
  next/components/ui/Bullet/Bullet.tsx
  next/components/ui/CallToAction/CallToAction.tsx
  next/components/ui/CheckBox/CheckBox.tsx
  next/components/ui/ColumnedText/ColumnedText.tsx
  next/components/ui/FlatText/FlatText.tsx
  next/components/ui/FlatTextCenter/FlatTextCenter.tsx
  next/components/ui/Input/Input.tsx
  next/components/ui/Listing/Listing.tsx
  next/components/ui/PageTitle/PageTitle.tsx
  next/components/ui/Partner/Partner.tsx
  next/components/ui/Radio/Radio.tsx
  next/components/ui/RadioGroup/RadioGroup.tsx
  next/components/ui/RowSubcategory/RowSubcategory.tsx
  next/components/ui/SearchBar/SearchBar.tsx
  next/components/ui/SubpageItem/SubpageItem.tsx
  next/components/ui/Table/Table.tsx
  next/components/ui/TableRow/TableRow.tsx
  next/components/ui/TextArea/TextArea.tsx
  next/components/ui/Upload/Upload.tsx
  next/graphql/queries/BlogPosts.graphql
  next/graphql/queries/Events.graphql
  next/hooks/useSearch.ts
  next/modules/common/MDatePicker/MDatePicker.css
  next/pages/404.tsx
  next/pages/search.tsx
  next/styles/globals.css
  next/styles/index.css
  next/utils.js
  next/utils/types.ts
Labels: needs review :pray:

#89 Next 13 update + fonts + header + footer
  next/.eslintrc.js
  next/assets/fonts/Bold/BeausiteClassicWeb-Bold.woff
  next/assets/fonts/Bold/BeausiteClassicWeb-Bold.woff2
  next/assets/fonts/Medium/BeausiteClassicWeb-Medium.woff
  next/assets/fonts/Medium/BeausiteClassicWeb-Medium.woff2
  next/assets/fonts/Regular/BeausiteClassicWeb-Regular.woff
  next/assets/fonts/Regular/BeausiteClassicWeb-Regular.woff2
  next/components/AppLayout/Header.tsx
  next/components/AppLayout/MobileNavigation/MobileHeader.tsx
  next/components/AppLayout/MobileNavigation/MobileNavigation.tsx
  next/components/AppLayout/MobileNavigation/MobileSubnavigation.tsx
  next/components/AppLayout/Navigation/HeaderNavigation.tsx
  next/components/AppLayout/Navigation/HeaderNavigationItem.tsx
  next/components/AppLayout/Navigation/NavigationItem.tsx
  next/components/AppLayout/Navigation/SubnavigationColumn.tsx
  next/components/HomePage/Promos/PromoEventCard.tsx
  next/components/HomePage/SectionLocalities.tsx
  next/components/Molecules/Breadcrumbs.tsx
  next/components/pages/DocumentsPage.tsx
  next/components/pages/SearchPage.tsx
  next/components/ui/Footer/Footer.tsx
  next/components/ui/Link/Link.tsx
  next/hooks/useEventsPaginated.ts
  next/hooks/usePagesPaginated.ts
  next/modules/common/MLink.tsx
  next/package.json
  next/pages/_app.tsx
  next/pages/api/revalidate.ts
  next/styles/city-library.css
  next/styles/index.css
  next/tailwind.config.js
  next/utils/beausiteFont.ts
  next/yarn.lock
Labels: needs review :pray:

#90 MKB-658: premises + branches cleanup
  next/components/Molecules/BranchCard.tsx
  next/components/Molecules/PremiseCard.tsx
  next/components/Molecules/Sections.tsx
  next/components/pages/localityPage.tsx
  next/components/pages/premises.tsx
  next/graphql/index.ts
  next/graphql/queries/Branches.graphql
  next/graphql/queries/queries.graphql
  next/pages/[...slug].tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  strapi/config/plugins.js
  strapi/src/api/blog-post/content-types/blog-post/schema.json
  strapi/src/api/branch/content-types/branch/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/premise/content-types/premise/schema.json
  strapi/src/api/premise/controllers/premise.js
  strapi/src/api/premise/routes/premise.js
  strapi/src/api/premise/services/premise.js
  strapi/src/components/blocks/branch-item-with-page.json
  strapi/src/components/sections/event-details.json
  strapi/src/components/sections/locality-details.json
  strapi/src/components/sections/rental.json
Labels: needs review :pray:

#95 MKB-660: update promo section height and layout
  next/components/Atoms/TagsDisplay.tsx
  next/components/HomePage/Promos/PromoEventCard.tsx
  next/components/HomePage/Promos/PromoNewsCard.tsx
  next/components/HomePage/SectionPromos.tsx
Labels: fix & ship :ship:

#97 New books v1
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/.env.development
  next/components/HomePage/SectionHomepageNewBooks.tsx
  next/components/HomePage/SectionOpacBookNews.tsx
  next/components/forms/FormFooter.tsx
  next/components/pages/bookNewsPage.tsx
  next/components/styleguide/StyleguideCards.tsx
  next/components/ui/BookNewsDetail/BookNewsDetail.tsx
  next/components/ui/index.ts
  next/modules/common/Cards/BookCard.tsx
  next/modules/providers/MQueryClientProvider.tsx
  next/modules/sections/NewBooksSection.tsx
  next/next.config.js
  next/package.json
  next/pages/_app.tsx
  next/pages/api/new-books.ts
  next/pages/index.tsx
  next/pages/styleguide.tsx
  next/public/locales/en/homepage.json
  next/public/locales/sk/homepage.json
  next/utils/fetchers/new-books-server-side.fetcher.ts
  next/utils/fetchers/new-books.fetcher.ts
  next/utils/mockNewBooks.ts
  next/utils/newBooksService.ts
  next/utils/opac.ts
  next/yarn.lock
Labels: needs review :pray:

#98 MKB-576: remove google analytics and cookie consent
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/.env.development
  next/components/Molecules/CookieConsent.tsx
  next/next.config.js
  next/package.json
  next/pages/_app.tsx
  next/pages/_document.tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  next/yarn.lock
Labels: fix & ship :ship:

#101 Sections
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/blog-posts-listing.json
  strapi/src/components/sections/documents-listing.json
  strapi/src/components/sections/events-listing.json
  strapi/src/components/sections/new-books-listing.json
  strapi/src/components/sections/news-listing.json
  strapi/src/components/sections/parnters.json
  strapi/src/components/sections/partners.json
Labels: needs review :pray:

#104 Partners + new books
  next/components/Molecules/Sections.tsx
  next/components/pages/bookNewsPage.tsx
  next/components/pages/partnersPage.tsx
  next/components/ui/Partner/PartnerSkeleton.tsx
  next/modules/sections/NewBooksSection.tsx
  next/modules/sections/PartnersSection.tsx
  next/pages/[...slug].tsx
  next/utils/fetchers/new-books.fetcher.ts
  next/utils/fetchers/partners.fetcher.tsx
Labels: needs review :pray:

#112 Fixes search notice
  next/backend/meili/fetchers/commonSearchFetcher.ts
  next/components/HomePage/Promos/PromoNewsCard.tsx
  next/components/HomePage/SectionHomepageNewBooks.tsx
  next/components/pages/SearchPage.tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  strapi/config/plugins.js
Labels: needs review :pray:

#108 MKB-665: refactor breadcrumbs, improve accessibility
  next/components/Molecules/Breadcrumbs.tsx
  next/components/Molecules/PageBreadcrumbs.tsx
  next/components/ScrollToTop.tsx
  next/components/pages/BranchPage.tsx
  next/components/pages/NoticePage.tsx
  next/components/pages/SearchPage.tsx
  next/components/pages/blogPostPage.tsx
  next/components/pages/eventPage.tsx
  next/components/styleguide/StyleguideBreadcrumbs.tsx
  next/components/ui/Breadcrumbs/Breadcrumbs.tsx
  next/components/ui/index.ts
  next/modules/breadcrumbs/BreadcrumbItem.tsx
  next/modules/breadcrumbs/Breadcrumbs.tsx
  next/modules/breadcrumbs/DesktopBreadcrumbs.tsx
  next/modules/breadcrumbs/MobileBreadcrumbs.tsx
  next/modules/common/Accordion.tsx
  next/modules/common/MLink.tsx
  next/pages/styleguide.tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
Labels: fix & ship :ship:

#109 MKB-642: richtext
  next/components/AppLayout/Navigation/SubnavigationColumn.tsx
  next/components/Atoms/CityLibraryMarkdown.tsx
  next/components/HomePage/Promos/PromoEventCard.tsx
  next/components/HomePage/SectionFaq.tsx
  next/components/Molecules/EventDetails.tsx
  next/components/Molecules/EventListingCard.tsx
  next/components/Molecules/ListingCard.tsx
  next/components/Molecules/LocalityDetails/LocalityDetails.tsx
  next/components/forms/EventReservationForm/index.tsx
  next/components/pages/BasicDocumentPage.tsx
  next/components/pages/blogPostPage.tsx
  next/components/pages/sidebarContentPage.tsx
  next/components/ui/ArticleCard/ArticleCard.tsx
  next/components/ui/ColumnedText/ColumnedText.tsx
  next/components/ui/Faq/Faq.tsx
  next/components/ui/FlatText/FlatText.tsx
  next/components/ui/FlatTextCenter/FlatTextCenter.tsx
  next/components/ui/PageTitle/PageTitle.tsx
  next/components/ui/RowFile/RowFile.tsx
  next/components/ui/SubpageItem/SubpageItem.tsx
  next/modules/common/MLink.tsx
  next/modules/formatting/FormatDate.tsx
  next/modules/formatting/FormatEventDateRange.tsx
  next/modules/formatting/NormalizeText/NormalizeText.tsx
  next/modules/formatting/NormalizeText/normalizeSkText.ts
  next/modules/formatting/RichText.tsx
  next/modules/providers/MI18nProvider.tsx
  next/pages/_app.tsx
  next/styles/city-library.css
  next/styles/globals.css
  next/styles/index.css
  next/utils/ui-context.tsx
Labels: fix & ship :ship:

#114 Events
  next/backend/meili/fetchers/eventsFetcher.ts
  next/backend/meili/meiliTypes.ts
  next/components/Molecules/EventFilters.tsx
  next/components/Molecules/EventListingCard.tsx
  next/components/Molecules/FilterModal.tsx
  next/components/Molecules/Sections.tsx
  next/components/pages/eventsListingPage.tsx
  next/modules/sections/EventsListingSection.tsx
  next/package.json
  next/pages/[...slug].tsx
  next/utils/meiliTypes.ts
  next/utils/prefetchPageSections.ts
  next/yarn.lock
  strapi/config/plugins.js
Labels: needs review :pray:

#115 Bugfix/mkb 674/submitting forms
  next/components/forms/FormFooter.tsx
Labels: needs review :pray:

#118 General context + react query/prefetching everywhere
  next/backend/meili/fetchers/commonSearchFetcher.ts
  next/components/AppLayout/Header.tsx
  next/components/AppLayout/MobileNavigation/MobileHeader.tsx
  next/components/AppLayout/MobileNavigation/MobileNavigation.tsx
  next/components/AppLayout/Navigation/NavigationItem.tsx
  next/components/AppLayout/Navigation/Subnavigation.tsx
  next/components/AppLayout/Navigation/SubnavigationColumn.tsx
  next/components/Atoms/Documents/DocumentsCategorySelect.tsx
  next/components/Atoms/SelectWithFetcher.tsx
  next/components/Molecules/EventFilters.tsx
  next/components/layouts/DefaultPageLayout.tsx
  next/components/pages/BasicDocumentPage.tsx
  next/components/pages/SearchPage.tsx
  next/components/pages/eventPage.tsx
  next/components/pages/listingPage.tsx
  next/graphql/index.ts
  next/graphql/queries/Branches.graphql
  next/graphql/queries/Events.graphql
  next/graphql/queries/Pages.graphql
  next/graphql/queries/queries.graphql
  next/hooks/useEventsPaginated.ts
  next/hooks/useGetSwrExtras.ts
  next/hooks/usePagesPaginated.ts
  next/hooks/useSwrWithExtras.ts
  next/hooks/useUpcomingEvets.ts
  next/next.config.js
  next/package.json
  next/pages/[...slug].tsx
  next/pages/basic-document/[slug].tsx
  next/pages/blog-post/[...fullPath].tsx
  next/pages/branch/[...fullPath].tsx
  next/pages/event/[...fullPath].tsx
  next/pages/index.tsx
  next/pages/notice/[...fullPath].tsx
  next/pages/search.tsx
  next/utils/fetchers/document-categories.fetcher.tsx
  next/utils/fetchers/event-properties.fetcher.ts
  next/utils/fetchers/general.fetcher.ts
  next/utils/fetchers/latestNews.fetcher.ts
  next/utils/generalContext.tsx
  next/utils/prefetchPageSections.ts
  next/yarn.lock
Labels: needs review :pray:

#125 MKB-570 - Introduced google calendar to form
  next/components/forms/SpaceReservationForm/index.tsx
Labels: needs review :pray:

#133 Fix normalize sk text
  next/modules/formatting/NormalizeText/normalizeSkText.ts
Labels: fix & ship :ship:

#139 MKB-688: introduce same logic to ssr and error page handling
  next/components/pages/BasicDocumentPage.tsx
  next/components/pages/ErrorPage.tsx
  next/components/pages/NoticePage.tsx
  next/next-i18next.config.js
  next/next.config.js
  next/pages/404.tsx
  next/pages/[...fullPath].tsx
  next/pages/[...slug].tsx
  next/pages/_app.tsx
  next/pages/basic-document/[...fullPath].tsx
  next/pages/basic-document/[slug].tsx
  next/pages/blog-post/[...fullPath].tsx
  next/pages/branch/[...fullPath].tsx
  next/pages/event/[...fullPath].tsx
  next/pages/index.tsx
  next/pages/notice/[...fullPath].tsx
  next/services/graphql/index.ts
  next/services/graphql/queries/BasicDocuments.graphql
  next/services/graphql/queries/Notices.graphql
  next/services/graphql/queries/queries.graphql
  next/utils/utils.ts
Labels: fix & ship :ship:

#141 feat: Added variables to requests resources CPU/Mem
  next/kubernetes/base/deployment.yml
  next/kubernetes/envs/Dev/config.json
  next/kubernetes/envs/Prod/config.json
  next/kubernetes/envs/Staging/config.json
  strapi/kubernetes/base/deployment.yml
  strapi/kubernetes/base/stateful-set-meilisearch.yml
  strapi/kubernetes/base/stateful-set.yml
  strapi/kubernetes/envs/Dev/config.json
  strapi/kubernetes/envs/Prod/config.json
  strapi/kubernetes/envs/Staging/config.json
Labels: infrastructure

#134 MKB-671 create generic component Carousel
  next/components/HomePage/Promos/PromoEventCard.tsx
  next/components/HomePage/SectionHomepageNewBooks.tsx
  next/components/HomePage/SectionLibraryNews.tsx
  next/components/HomePage/SectionPromos.tsx
  next/components/HomePage/VerticalCardButton.tsx
  next/components/Molecules/Carousel/Carousel.tsx
  next/components/Molecules/Carousel/SliderControl/SliderControl.tsx
  next/modules/common/Button.tsx
  next/tailwind.config.js
Labels: fix & ship :ship:

#142 Forms - bunch of smaller bugfixes
  next/components/HomePage/SectionTags.tsx
  next/components/forms/InterlibraryLoanServiceFormReader/index.tsx
  next/components/forms/RechercheReservationForm/index.tsx
  next/components/forms/TabletReservationForm/options.ts
  next/components/ui/RadioGroup/RadioGroup.tsx
  next/public/locales/en/forms.json
  next/public/locales/sk/common.json
  next/tailwind.config.js
Labels: fix & ship :ship:
