Repository bratislava/mestskakniznica.sk, pull requests merged in 2025-01, with the labels that each got.

#353 #347 Adjust the content of the Registration form
  next/components/forms/CityLibraryRegistrationForm/options.ts
Labels: needs review :pray:

#355 #348 Adjust the Registration form to accept both IDs and passports
  next/components/forms/FormContainer.tsx
  next/public/locales/en/forms.json
Labels: needs review :pray:

#356 #348 Adjust the wording of SK and EN error message for ID number field
  next/public/locales/en/forms.json
  next/public/locales/sk/forms.json
Labels: needs review :pray:

#358 #344 Add `isCurrentChangeInOpeningHours` flag to BlogPosts in Strapi
  next/services/graphql/index.ts
  strapi/schema.graphql
  strapi/src/api/blog-post/content-types/blog-post/schema.json
Labels: pr: fix & ship :ship:

#357 #308 Refactor focus ring behaviour
  next/components/AppLayout/Header.tsx
  next/components/AppLayout/Navigation/HeaderNavigation.tsx
  next/components/Atoms/SelectField.tsx
  next/components/Atoms/TagToggle.tsx
  next/components/Atoms/TextField.tsx
  next/components/HomePage/SectionPromos.tsx
  next/components/Molecules/EventDetails.tsx
  next/components/forms/FormContainer.tsx
  next/components/forms/StepNumberTitle.tsx
  next/components/pages/SearchPage.tsx
  next/components/ui/CheckBox/CheckBox.tsx
  next/components/ui/Footer/Footer.tsx
  next/components/ui/Input/Input.tsx
  next/components/ui/Link/Link.tsx
  next/components/ui/MapSection/MapSection.tsx
  next/components/ui/RadioGroup/RadioGroup.tsx
  next/components/ui/Select/Select.tsx
  next/components/ui/TextArea/TextArea.tsx
  next/components/ui/Upload/Upload.tsx
  next/modules/breadcrumbs/BreadcrumbItem.tsx
  next/modules/cards-and-rows/BlogPostCard.tsx
  next/modules/cards-and-rows/BookCard.tsx
  next/modules/cards-and-rows/BranchCard.tsx
  next/modules/cards-and-rows/CardWrapper.tsx
  next/modules/cards-and-rows/DocumentRow.tsx
  next/modules/cards-and-rows/EventCard.tsx
  next/modules/cards-and-rows/EventRow.tsx
  next/modules/cards-and-rows/NoticeCard.tsx
  next/modules/cards-and-rows/PageCard.tsx
  next/modules/cards-and-rows/PartnerCardRow.tsx
  next/modules/cards-and-rows/PromoEventCard.tsx
  next/modules/cards-and-rows/PromoNewsCard.tsx
  next/modules/common/Accordion.tsx
  next/modules/common/Button.tsx
  next/modules/common/ImageGallery/ImageGallery.tsx
  next/modules/common/MDatePicker/MDatePicker.tsx
  next/modules/common/MLink.tsx
  next/modules/navigation/MobileLatestEvents.tsx
  next/modules/navigation/NavMenuLatestEvents.tsx
  next/modules/navigation/NavMenuTrigger.tsx
  next/modules/sections/PartnersSection.tsx
  next/styles/globals.css
Labels: pr: needs review :pray:

#359 #344 Show banner with current change of opening hours
  next/components/Molecules/BranchDetails/ContactsAndOpeningHours.tsx
  next/components/Molecules/OpeningHoursChangeAlert.tsx
  next/modules/sections/OpeningHoursSection.tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  next/services/graphql/index.ts
  next/services/graphql/queries/Notices.graphql
  strapi/schema.graphql
  strapi/src/api/blog-post/content-types/blog-post/schema.json
  strapi/src/api/notice/content-types/notice/schema.json
Labels: pr: needs review :pray:

#360 #362 Upgrade Strapi to 4.11.4
  strapi/config/database.js
  strapi/database/migrations/2023.06.14T00.00.00.update-file-paths.js
  strapi/package.json
  strapi/src/plugins/navikronos/package.json
  strapi/src/plugins/navikronos/yarn.lock
  strapi/yarn.lock
Labels: pr: needs review :pray:

#369 #284 Unify card image ratio
  next/modules/cards-and-rows/BlogPostCard.tsx
  next/modules/cards-and-rows/BranchCard.tsx
  next/modules/cards-and-rows/EventCard.tsx
  next/modules/cards-and-rows/NoticeCard.tsx
  next/tailwind.config.js
Labels: pr: needs review :pray:

#368 Add PR labeler
  .github/workflows/label.yml
Labels: pr: fix & ship :ship:

#361 #308 Fix focus ring issues - "cropped focus rings"
  next/components/HomePage/SectionHomepageNewBooks.tsx
  next/components/HomePage/SectionPromos.tsx
  next/components/Molecules/BranchDetails/BranchDetails.tsx
  next/components/pages/SearchPage.tsx
  next/components/ui/MapSection/MapSection.tsx
  next/modules/breadcrumbs/DesktopBreadcrumbs.tsx
  next/modules/common/Carousel/Carousel.tsx
Labels: pr: fix & ship :ship:

#367 #364 Allow crawling only on prod
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/.env.development
  next/next.config.js
  next/pages/api/robots.ts
  next/utils/utils.ts
Labels: pr: fix & ship :ship:

#373 #308 focus rings additional improvements
  next/components/HomePage/SectionLibraryNews.tsx
Labels: pr: fix & ship :ship:

#375 #363 Update Gift certificate form
  next/components/forms/GiftCardReservationForm/options.ts
Labels: pr: fix & ship :ship:

#354 #350 Update Excursion form's content
  next/components/forms/ExcursionReservationForm/index.tsx
  next/components/forms/ExcursionReservationForm/options.ts
  next/pages/api/submit-form.ts
Labels: pr: fix & ship :ship:

#280 feat: added KEDA (HPA) Prometheus scalers
  next/kubernetes/envs/Dev/kustomization.yml
  next/kubernetes/envs/Dev/scaler.yml
  next/kubernetes/envs/Prod/kustomization.yml
  next/kubernetes/envs/Prod/scaler.yml
  next/kubernetes/envs/Staging/kustomization.yml
  next/kubernetes/envs/Staging/scaler.yml
  strapi/kubernetes/envs/Dev/config.json
  strapi/kubernetes/envs/Dev/kustomization.yml
  strapi/kubernetes/envs/Dev/scaler.yml
  strapi/kubernetes/envs/Prod/config.json
  strapi/kubernetes/envs/Prod/kustomization.yml
  strapi/kubernetes/envs/Prod/scaler.yml
  strapi/kubernetes/envs/Staging/config.json
  strapi/kubernetes/envs/Staging/kustomization.yml
  strapi/kubernetes/envs/Staging/scaler.yml
Labels: infrastructure, pr: fix & ship :ship:

#371 Upgrade strapi to 4.14.0
  strapi/package.json
  strapi/schema.graphql
  strapi/src/plugins/navikronos/package.json
  strapi/src/plugins/navikronos/yarn.lock
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
  strapi/yarn.lock
Labels: pr: fix & ship :ship:
